CLIENT = Client.java

all : Client.class

Client.class : Client.java
	@echo -n Compiling client...
	@javac Client.java
	@echo Done

clean:
	@echo -n Deleting class files...
	@rm -rf *.class
	@echo Done
